name: Deploy database to dev
on: workflow_dispatch
permissions: {}
env:
  DATABASE_IMAGE_NAME: postgres:17.2-alpine
  DATABASE_NET_NAME: database
  DATABASE_CONTAINER_NAME: database
jobs:
  Run_container:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run start database script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image inspect ${{ env.DATABASE_IMAGE_NAME }} &> /dev/null || docker pull ${{ env.DATABASE_IMAGE_NAME }}
            docker network inspect ${{ env.DATABASE_NET_NAME }} &> /dev/null || docker network create --driver bridge ${{ vars.POSTGRES_NET_NAME }}
            docker container inspect ${{ env.DATABASE_CONTAINER_NAME }} db &> /dev/null && docker stop ${{ env.DATABASE_CONTAINER_NAME }}
            docker container inspect ${{ env.DATABASE_CONTAINER_NAME }} db &> /dev/null || docker run --rm -it -p 5432:5432 --network ${{ vars.POSTGRES_NET_NAME }} --name ${{ env.DATABASE_CONTAINER_NAME }} -e POSTGRES_USER=user -e POSTGRES_PASSWORD=pass ${{ env.DATABASE_IMAGE_NAME }}

