name: Deploy database to dev
on: workflow_dispatch
permissions: {}
env:
  DATABASE_IMAGE: postgres:17.2-alpine
  DATABASE_NET: database
  DATABASE_CONTAINER: database
  DATABASE_NAME: cicd
jobs:
  Run_container:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run start database script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image inspect ${{ env.DATABASE_IMAGE }} &> /dev/null || docker pull ${{ env.DATABASE_IMAGE }}
            docker network inspect ${{ env.DATABASE_NET }} &> /dev/null || docker network create --driver bridge ${{ vars.POSTGRES_NET_NAME }}
            docker container inspect ${{ env.DATABASE_CONTAINER }} &> /dev/null && docker stop ${{ env.DATABASE_CONTAINER }}
            docker container inspect ${{ env.DATABASE_CONTAINER }} &> /dev/null || docker run --rm -dit \
              -p 5432:5432 \
              --network ${{ vars.POSTGRES_NET_NAME }} \
              --name ${{ env.DATABASE_CONTAINER }} \
              -e POSTGRES_USER="${{ secrets.DATABASE_USER }}" \
              -e POSTGRES_PASSWORD="${{ secrets.DATABASE_PASS }}" \
              -e POSTGRES_DB="${{ env.DATABASE_NAME }}" \
              ${{ env.DATABASE_IMAGE }}

