name: Deploy database to dev
on: workflow_dispatch
permissions: {}
env:
  DATABASE_IMAGE_NAME: postgres:17.2-alpine
jobs:
  Run_container:
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run script to
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image inspect ${{ env.DATABASE_IMAGE_NAME }} &> /dev/null || docker pull ${{ env.DATABASE_IMAGE_NAME }}
            docker network inspect ${{ vars.POSTGRES_NET_NAME }} &> /dev/null || echo "creating network..."
#            docker network inspect ${{ vars.POSTGRES_NET_NAME }} &> /dev/null || docker network create --driver bridge ${{ vars.POSTGRES_NET_NAME }}
#            docker inspect db &> /dev/null && docker run --rm -dit -p 5432:5432 --network ${{ vars.POSTGRES_NET_NAME }} --name db postgres:17.2-alpine
            
